CREATE TABLE login (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    usuario VARCHAR(255) NOT NULL UNIQUE,
    senha VARCHAR(255) NOT NULL,
    tipo_conta ENUM('ADMINISTRATIVO', 'ASSISTENTE_SOCIAL', 'CLIENTE') NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE
);